#!/usr/bin/env bash
# Script that installs Nginx server

apt-get -y update
apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo service nginx reload
